### ISSUE TITLE
MPC code and general discussion on RL observation

### ISSUE THREAD

**Issue by adeebislam8** [dasGringuen/assetto_corsa_gym#1]
Amazing work here! Was looking for a AC interface for RL training for a while since I was experimenting with TD-MPC2 vs SAC vs MPC for autonomous racing too. I ended up using CARLA hahaha.

I was wondering if you intend to upload your MPC code here. I am not quite happy with my implementation so would love to see how you went about doing it.

Another question regarding your RL observations. From what I understood you are using telemetry data instead of any high-level observation such as RGB image. I was wondering if you plan to extend your work using higher dimension observations. In my case TD-MPC2 performed really bad with just rgb images and very basic telemetry information such as a speed and control.

Thanks for the repo!

**Comment by ayoubraji** [comment]
Hi!
The MPC used in the paper cannot be published at the moment because it is still part of an ongoing applied research and could be used in some autonomous racing competitions where we would keep a possible competitive advantage.
I am willing to publish an open-source version of it in the next year but I have not properly planned it yet. 

You can find an older version online at https://github.com/alexliniger/MPCC
and following the references we put on the paper you could catch the differences.
It will not perform the same but it's a valid baseline.

**Comment by dasGringuen** [comment]
Regarding the RL observations, yes, we just use states (telemetry) here.
Supporting RGB images is in our roadmap. Compute is a limitation here as the simulation runs in real-time only. Maybe reducing the frequency to 10 Hz instead of 25 Hz would help. In the state only version, this degraded the performance.

**Comment by adeebislam8** [comment]
Thanks for the responses!
